version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '3100:3100'
    networks:
      - app
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: >
      sh -c "npm run start"
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    networks:
      - app
    volumes:
      - ./website:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: >
      sh -c "npm run dev"

networks:
  app:
    driver: bridge